In [1]:
import numpy as np

In [2]:
# 对应状态集合Q
states = ('Healthy', 'Fever')
# 对应观测集合V
observations = ('normal', 'cold', 'dizzy')
# 初始状态概率向量π
start_probability = {'Healthy': 0.6, 'Fever': 0.4}
# 状态转移矩阵A
transition_probability = {
    'Healthy': {'Healthy': 0.7, 'Fever': 0.3},
    'Fever': {'Healthy': 0.4, 'Fever': 0.6},
}
# 观测概率矩阵B
emission_probability = {
    'Healthy': {'normal': 0.5, 'cold': 0.4, 'dizzy': 0.1},
    'Fever': {'normal': 0.1, 'cold': 0.3, 'dizzy': 0.6},
}

In [3]:
def generate_index_map(lables):
    id2label = {}
    label2id = {}
    i = 0
    for l in lables:
        id2label[i] = l
        label2id[l] = i
        i += 1
    return id2label, label2id
 
states_id2label, states_label2id = generate_index_map(states)
observations_id2label, observations_label2id = generate_index_map(observations)
print(states_id2label, states_label2id)
print(observations_id2label, observations_label2id)

{0: 'Healthy', 1: 'Fever'} {'Healthy': 0, 'Fever': 1}
{0: 'normal', 1: 'cold', 2: 'dizzy'} {'normal': 0, 'cold': 1, 'dizzy': 2}


In [4]:
def convert_map_to_vector(map_, label2id):
    """将概率向量从dict转换成一维array"""
    v = np.zeros(len(map_), dtype=float)
    for e in map_:
        v[label2id[e]] = map_[e]
    return v

 
def convert_map_to_matrix(map_, label2id1, label2id2):
    """将概率转移矩阵从dict转换成矩阵"""
    m = np.zeros((len(label2id1), len(label2id2)), dtype=float)
    for line in map_:
        for col in map_[line]:
            m[label2id1[line]][label2id2[col]] = map_[line][col]
    return m

In [5]:
A = convert_map_to_matrix(transition_probability, states_label2id, states_label2id)
print(A)
B = convert_map_to_matrix(emission_probability, states_label2id, observations_label2id)
print(B)
observations_index = [observations_label2id[o] for o in observations]
pi = convert_map_to_vector(start_probability, states_label2id)
print(pi)

[[0.7 0.3]
 [0.4 0.6]]
[[0.5 0.4 0.1]
 [0.1 0.3 0.6]]
[0.6 0.4]


In [6]:
# 随机生成观测序列和状态序列    
def simulate(T):

    def draw_from(probs):
        """
        1.np.random.multinomial:
        按照多项式分布，生成数据
        >>> np.random.multinomial(20, [1/6.]*6, size=2)
                array([[3, 4, 3, 3, 4, 3],
                       [2, 4, 3, 4, 0, 7]])
         For the first run, we threw 3 times 1, 4 times 2, etc.  
         For the second, we threw 2 times 1, 4 times 2, etc.
        2.np.where:
        >>> x = np.arange(9.).reshape(3, 3)
        >>> np.where( x > 5 )
        (array([2, 2, 2]), array([0, 1, 2]))
        """
        return np.where(np.random.multinomial(1,probs) == 1)[0][0]

    observations = np.zeros(T, dtype=int)
    states = np.zeros(T, dtype=int)
    states[0] = draw_from(pi)
    observations[0] = draw_from(B[states[0],:])
    for t in range(1, T):
        states[t] = draw_from(A[states[t-1],:])
        observations[t] = draw_from(B[states[t],:])
    return observations, states

In [7]:
# 生成模拟数据
observations_data, states_data = simulate(10)
print(observations_data)
print(states_data)
# 相应的label
print("病人的状态: ", [states_id2label[index] for index in states_data])
print("病人的观测: ", [observations_id2label[index] for index in observations_data])

[0 1 0 2 0 2 2 2 1 0]
[0 0 0 1 0 1 0 1 0 0]
病人的状态:  ['Healthy', 'Healthy', 'Healthy', 'Fever', 'Healthy', 'Fever', 'Healthy', 'Fever', 'Healthy', 'Healthy']
病人的观测:  ['normal', 'cold', 'normal', 'dizzy', 'normal', 'dizzy', 'dizzy', 'dizzy', 'cold', 'normal']


## offline 

In [8]:
def forward(obs_seq):
    """前向算法"""
    N = A.shape[0]
    T = len(obs_seq)
    
    # F保存前向概率矩阵
    F = np.zeros((N,T))
    F[:,0] = pi * B[:, obs_seq[0]]

    for t in range(1, T):
        for n in range(N):
            F[n,t] = np.dot(F[:,t-1], (A[:,n])) * B[n, obs_seq[t]]

    return F

def backward(obs_seq):
    """后向算法"""
    N = A.shape[0]
    T = len(obs_seq)
    # X保存后向概率矩阵
    X = np.zeros((N,T))
    X[:,-1:] = 1
#     print("x: ", X)

    for t in reversed(range(T-1)):
        for n in range(N):
#             dd = X[:,t+1] * A[n,:] * B[:, obs_seq[t+1]]
#             print(dd)
            X[n,t] = np.sum(X[:,t+1] * A[n,:] * B[:, obs_seq[t+1]])

    return X

In [9]:
forward(observations_data)

array([[3.00000000e-01, 9.04000000e-02, 3.84800000e-02, 2.88416000e-03,
        2.73774400e-03, 2.15842528e-04, 4.35328950e-05, 1.48339794e-05,
        2.23800761e-05, 1.22010147e-05],
       [4.00000000e-02, 3.42000000e-02, 4.76400000e-03, 8.64144000e-03,
        6.05011200e-04, 7.10597952e-04, 2.94666918e-04, 1.13916012e-04,
        2.18399402e-05, 1.98179869e-06]])

In [10]:
backward(observations_data)

array([[4.24909145e-05, 1.22733385e-04, 3.10365390e-04, 1.50547499e-03,
        3.74432060e-03, 9.89882000e-03, 2.84540000e-02, 1.29800000e-01,
        3.80000000e-01, 1.00000000e+00],
       [3.58884751e-05, 9.02840749e-05, 4.70183281e-04, 1.13878967e-03,
        6.49875920e-03, 1.69522400e-02, 4.39280000e-02, 1.07600000e-01,
        2.60000000e-01, 1.00000000e+00]])

In [11]:
def baum_welch_train(observations, A, B, pi, criterion=0.05):
    """无监督学习算法——Baum-Weich算法"""
    n_states = A.shape[0]
    n_samples = len(observations)

    done = False
    while not done:
        # alpha_t(i) = P(O_1 O_2 ... O_t, q_t = S_i | hmm)
        # Initialize alpha
        alpha = forward(observations)

        # beta_t(i) = P(O_t+1 O_t+2 ... O_T | q_t = S_i , hmm)
        # Initialize beta
        beta = backward(observations)
        # ξ_t(i,j)=P(i_t=q_i,i_{i+1}=q_j|O,λ)
        xi = np.zeros((n_states,n_states,n_samples-1))
        for t in range(n_samples-1):
            denom = np.dot(np.dot(alpha[:,t].T, A) * B[:,observations[t+1]].T, beta[:,t+1])
            for i in range(n_states):
                numer = alpha[i,t] * A[i,:] * B[:,observations[t+1]].T * beta[:,t+1].T
                xi[i,:,t] = numer / denom

        # γ_t(i)：gamma_t(i) = P(q_t = S_i | O, hmm)
        gamma = np.sum(xi,axis=1)
        # Need final gamma element for new B
        # xi的第三维长度n_samples-1，少一个，所以gamma要计算最后一个
        prod =  (alpha[:,n_samples-1] * beta[:,n_samples-1]).reshape((-1,1))
        gamma = np.hstack((gamma,  prod / np.sum(prod))) #append one more to gamma!!!
        
        # 更新模型参数
        newpi = gamma[:,0]
        newA = np.sum(xi,2) / np.sum(gamma[:,:-1],axis=1).reshape((-1,1))
        newB = np.copy(B)
        num_levels = B.shape[1]
        sumgamma = np.sum(gamma,axis=1)
        for lev in range(num_levels):
            mask = observations == lev
            newB[:,lev] = np.sum(gamma[:,mask],axis=1) / sumgamma
        
        # 检查是否满足阈值
        if np.max(abs(pi - newpi)) < criterion and \
                        np.max(abs(A - newA)) < criterion and \
                        np.max(abs(B - newB)) < criterion:
            done = 1
        A[:], B[:], pi[:] = newA, newB, newpi
    return newA, newB, newpi

In [12]:
A = np.array([[0.5, 0.5],[0.5, 0.5]])
B = np.array([[0.3, 0.3, 0.4],[0.3, 0.3, 0.4]])
pi = np.array([0.4, 0.6])
print("pi: ", pi)
pic = pi.copy()

observations_data, states_data = simulate(200)
newA, newB, newpi = baum_welch_train(observations_data, A, B, pic,0.02)
print("newA: ", newA)
print("newB: ", newB)
print("newpi: ", newpi)
print("pi: ", pi)


pi:  [0.4 0.6]
newA:  [[0.50000395 0.49999605]
 [0.50000498 0.49999502]]
newB:  [[0.29058048 0.35871895 0.35070058]
 [0.28942068 0.36127849 0.34930082]]
newpi:  [0.39914697 0.60085303]
pi:  [0.4 0.6]


## online
Online Learning with Hidden Markov Models[ Gianluigi Mongillo ,Sophie Deneve]

Start with: 
- initial guess for the model parameters, θ(0) = [A,B], 
- initial state probabilities, ˆql (0) ≡ P(x0 = l), 
- sufficient statistics, ˆφh ijk(0)

specific data struct


In [ ]:
import numpy as np

In [ ]:
# 初始状态概率向量π
pi = np.array([0.5, 0.5])
print("初始状态概率向量π: ", pi)

In [ ]:
# 初始状态转移矩阵和观测矩阵
A = np.array([[0.5, 0.5],[0.5, 0.5]])
B = np.ones([2,3])/float(3)
print("初始状态转移矩阵A:\n", A)
print("初始观测矩阵A:\n", B)


In [ ]:
# P(xt−1 = i, xt = j, xT−1 = l, xT = h, y0→T)
# which element to update in transition model or observation mode
# i = 1 # xt-1
# j = 0 # xt

# observed  
# k = 0 #yT

# last two state
# l = 0 # xT-1
# h = 0 # xT

In [ ]:
time_factor = 0.001
print("time_factor: ", time_factor)

In [ ]:
# γlh(yT) 
# probility P(xT-1 = l, xT = h | yT = k)
Gama = 0.0*np.ones([2,2,3])
print("Gama:\n", Gama)

In [ ]:
# 状态概率 ql (T − 1) ≡ P(xT−1 = l|y0→T−1)
# probility P(xT-1 = l | y0-T-1)
Q = pi
print("状态概率：\n", Q)

In [ ]:
# 信息概率
# P(xt-1 = i, xt = j, xT = h , yT = h)
Fi = np.ones([2,2,2,3])/float(3)
print("信息概率:\n ", Fi)

In [ ]:
# initialise all probility with A B
Q0 = Q
print("Q0\n", Q0)

In [ ]:
# update after get observation
# get new obs
k = 0

# update Gama(T) from Q(T-1)
# Gama(l, h, k)
prob_sum = (A[0][0]*B[0][k]*Q[0] + A[0][1]*B[1][k]*Q[0] + A[1][0]*B[0][k]*Q[1] + A[1][1]*B[1][k]*Q[1]  )
Gama[0][0][k] = (A[0][0]*B[0][k]) / prob_sum
Gama[0][1][k] = (A[0][1]*B[1][k]) / prob_sum
Gama[1][0][k] = (A[1][0]*B[0][k]) / prob_sum
Gama[1][1][k] = (A[1][1]*B[1][k]) / prob_sum


# update internal state posibility
# Q(T) = Gama(T)*Q(T-1)

Q[0]
Q[0] = (Gama[0][0][k] * Q0[0]) + (Gama[1][0][k] * Q0[1])  
Q[1] = (Gama[0][1][k] * Q0[0]) + (Gama[1][1][k] * Q0[1])  
print("Q:\n", Q)

# P(xt-1 = i, xt = j, xT = h , yT = k)
# updata enven corespond yT is not observed
# Fi[0][0][0][0] = 0.0
# Fi[i][j][h][k] = Gama[l][h][k] * Fi[i][j][l][k] G(h,l) Q(l)
Fi[0][0][0][0]  = (Gama[0][0][k] * (Fi[0][0][0][0] + time_factor*(delta(0, k)*g_delta(0, 0 ,0, 0)*Q[0] - Fi[0][0][0][0] ) ) ) + \
     (Gama[1][0][k] * (Fi[0][0][1][0] + time_factor*(delta(0, k)*g_delta(0, 0 ,1, 0)*Q[1] - Fi[0][0][1][0] ) ) )

print("Fi(0,0,0,0)\n", Fi[0][0][0][0] )

In [ ]:
Fi

In [ ]:
Gama,Q,

In [20]:
def delta(i, j):
    if i == j:
        return 1
    else :
        return 0
def g_delta(i, j, l, h):
    return delta(i, l )*delta(j, h)


class Q_data:
    def __init__(self,Q_):
        self.Q = Q_
    
    def updateQ(self, new_obs_k, Gama_):
        Q0 = self.Q
        print("K: ", new_obs_k, "Gama: ", Gama_, "Q0: ", Q0)
        print("debug: ",Gama_[0][0][new_obs_k] ,", ", Q0[0],", ", Gama_[1][0][new_obs_k] ,",",  Q0[1]   )
        self.Q[0] = (Gama_[0][0][new_obs_k] * Q0[0]) + (Gama_[1][0][new_obs_k] * Q0[1])  

        self.Q[1] = (Gama_[0][1][new_obs_k] * Q0[0]) + (Gama_[1][1][new_obs_k] * Q0[1])  
        
        print("updated Q = \n", self.Q)

    def getQ(self):
        return self.Q

In [14]:
class Gama_data:
    def __init__(self, Gama_):
        self.Gama = Gama_
        self.prob_sum = None
        self.A = None
        self.B = None
    
    def updateModel(self, A_, B_):
        self.A = A_
        self.B = B_
        
    def updateGama(self, new_obs_k, Q_old):
        A_ = self.A
        B_ = self.B
        Q_ = Q_old
        print("debug nan ", A_, B_, Q_)
        prob_sum = (A_[0][0]*B_[0][new_obs_k]*Q_[0] + A_[0][1]*B_[1][new_obs_k]*Q_[0]\
                  + A_[1][0]*B_[0][new_obs_k]*Q_[1] + A_[1][1]*B_[1][new_obs_k]*Q_[1]  )
        self.prob_sum = prob_sum
        print (" (A[0][0]*B[0][k]) / prob_sum", (A_[0][0]*B_[0][new_obs_k]) , prob_sum)
        self.Gama[0][0][new_obs_k] = (A_[0][0]*B_[0][new_obs_k]) / prob_sum

        self.Gama[0][1][new_obs_k] = (A_[0][1]*B_[1][new_obs_k]) / prob_sum

        self.Gama[1][0][new_obs_k] = (A_[1][0]*B_[0][new_obs_k]) / prob_sum

        self.Gama[1][1][new_obs_k] = (A_[1][1]*B_[1][new_obs_k]) / prob_sum
        
    
    
    def get(self, i_, j_, k_):
        return self.Gama[i_][j_][k_]
        
    def getGama(self):
        return self.Gama
    
# how to define a datastruct
# member data
# method

# for Gama
# contatin latest Gama
# updata Gama from Q and yT, A, B
        

In [ ]:
m_gama = Gama_data(Gama)

In [ ]:
m_gama.updateModel(A,B)
m_gama.updateGama(new_obs_k=0,Q_old=Q0)

In [ ]:
Q0

In [ ]:
m_gama.getGama()

In [ ]:
m_q = Q_data(Q0)

In [ ]:
m_q.getQ()

In [ ]:
m_q.updateQ(0, m_gama.getGama())

In [ ]:
m_q.getQ()

In [ ]:
Q

In [15]:
class Fi_data:
    def __init__(self, Fi_, time_factor_):
        self.Fi = Fi_
        self.time_factor = time_factor_
        
    def updateMode(self,new_obs_k ,Gama_, Q_):
        for i in range(self.Fi.shape[0]):
            for j in range(self.Fi.shape[1]):
                for h in range(self.Fi.shape[2]):
                    for k in range(self.Fi.shape[3]):
                        self.Fi[i][j][h][k]  = (Gama_[0][h][k] * (self.Fi[i][j][0][k] + self.time_factor*(delta(new_obs_k, k)*g_delta(i, j ,0, h)*Q_[0] - self.Fi[i][j][0][k] ) ) ) + \
                                               (Gama_[1][h][k] * (self.Fi[i][j][1][k] + self.time_factor*(delta(new_obs_k, k)*g_delta(i, j ,1, h)*Q_[1] - self.Fi[i][j][1][k] ) ) )
                
    def getFi(self):
        return self.Fi;

In [ ]:
Gama

In [ ]:

m_fi = Fi_data(Fi, time_factor)

In [ ]:
m_fi.updateMode(0, m_gama.getGama(), m_q.getQ())

In [ ]:
m_fi.getFi() - hmm.fi.getFi()

In [ ]:
hmm.fi.getFi()

set state dim, observation dim
state_dim = 2
obs_dim = 3


In [21]:
class HMM:
    def __init__(self, state_dim_, obs_dim_):
        self.A = np.ones([state_dim_, state_dim_]) / float(state_dim_)
        self.B = np.ones([state_dim_, obs_dim_])/ float(obs_dim_)
        self.pi = np.ones([state_dim_])/ float(state_dim_)
        
        print("A:\n", self.A, "\nB:\n", self.B, "\npi:\n", self.pi)
        
        Gama_ = 0.0*np.ones([2,2,3])

        print("Gama:\n", Gama_)
        
        self.gama = Gama_data(Gama_)
        
        Q_ = self.pi
        
        self.q = Q_data(Q_)
        
        Fi_ = np.ones([state_dim_,state_dim_,state_dim_,obs_dim_])/float(obs_dim_)
        print("信息概率:\n ", Fi_)
        
        time_factor_ = 0.001
        
        self.fi = Fi_data(Fi_, time_factor_)
        
        
#         self.Q 
#         self.Gama
    def learn(self, data_):
        
        print("get data:\n", data_)
        
        for ob in data_:
            
#             updata gama
            self.gama.updateModel(self.A,self.B)
    
            print("debug gama:\n", self.gama.getGama(),self.q.getQ())
            self.gama.updateGama(new_obs_k=ob,Q_old=self.q.getQ())



#             updata q
            self.q.updateQ(ob, self.gama.getGama())

#             update fi
            self.fi.updateMode(ob, self.gama.getGama(), self.q.getQ())
    
        
#         only when all possible observation is detected
            
        if np.any(Gama == 0.0):
#             update A, B
        
            fi = self.fi.getFi()
           # fi(i,j,h,k)
            for i in range(self.A.shape[0]):
                for j in range(self.A.shape[1]):
                    self.A[i][j] = fi[i,j,:,:].sum() / fi[i,:,:,:].sum()
            
            for j in range(self.B.shape[0]):
                for k in range(self.B.shape[1]):
                    self.B[j][k] = fi[:,j,:,k].sum() / fi[:,j,:,:].sum()


            

In [22]:
state_dim = 2
obs_dim = 3
hmm = HMM(state_dim, obs_dim)

A:
 [[0.5 0.5]
 [0.5 0.5]] 
B:
 [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]] 
pi:
 [0.5 0.5]
Gama:
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
信息概率:
  [[[[0.33333333 0.33333333 0.33333333]
   [0.33333333 0.33333333 0.33333333]]

  [[0.33333333 0.33333333 0.33333333]
   [0.33333333 0.33333333 0.33333333]]]


 [[[0.33333333 0.33333333 0.33333333]
   [0.33333333 0.33333333 0.33333333]]

  [[0.33333333 0.33333333 0.33333333]
   [0.33333333 0.33333333 0.33333333]]]]


In [23]:
print("ground truth,observations_data\n",observations_data, "\nstates_data\n ",states_data)

ground truth,observations_data
 [1 0 1 2 2 0 0 2 2 1 1 0 2 1 0 0 0 1 1 2 0 1 1 2 1 2 2 2 2 2 1 1 1 0 0 2 2
 2 0 1 0 1 1 2 0 0 0 1 1 0 0 1 1 2 0 2 2 1 2 0 0 2 1 1 0 1 0 2 0 0 2 2 2 1
 0 1 0 0 2 2 1 1 0 2 0 1 2 1 1 2 1 1 2 2 1 0 0 0 0 2 0 0 0 1 1 2 1 2 0 2 0
 1 1 1 2 1 1 0 1 0 1 0 0 2 0 2 2 1 0 1 2 1 2 2 0 1 1 0 0 1 0 2 2 0 2 1 1 0
 2 1 2 2 2 0 2 2 0 0 2 1 2 2 0 0 1 2 2 0 2 1 1 1 0 1 2 2 1 2 1 2 1 1 2 2 1
 1 2 0 1 2 2 1 1 2 1 1 1 2 1 2] 
states_data
  [1 0 0 1 1 1 0 0 1 1 1 1 0 0 1 0 1 0 1 0 1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 1
 0 1 1 0 1 0 1 0 0 1 0 1 1 0 0 0 0 1 0 1 1 1 1 0 0 0 1 1 1 1 1 1 0 1 1 1 0
 0 1 1 0 0 1 0 1 1 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1
 1 1 1 1 1 1 1 0 0 0 0 1 1 1 0 1 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 0 0 0 0
 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 1 1 1 0 1 0 1 1 0 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 0 1 1 0 0 0 0 0 1 0 1 0 0 0]


In [24]:

hmm.learn(observations_data)

get data:
 [1 0 1 2 2 0 0 2 2 1 1 0 2 1 0 0 0 1 1 2 0 1 1 2 1 2 2 2 2 2 1 1 1 0 0 2 2
 2 0 1 0 1 1 2 0 0 0 1 1 0 0 1 1 2 0 2 2 1 2 0 0 2 1 1 0 1 0 2 0 0 2 2 2 1
 0 1 0 0 2 2 1 1 0 2 0 1 2 1 1 2 1 1 2 2 1 0 0 0 0 2 0 0 0 1 1 2 1 2 0 2 0
 1 1 1 2 1 1 0 1 0 1 0 0 2 0 2 2 1 0 1 2 1 2 2 0 1 1 0 0 1 0 2 2 0 2 1 1 0
 2 1 2 2 2 0 2 2 0 0 2 1 2 2 0 0 1 2 2 0 2 1 1 1 0 1 2 2 1 2 1 2 1 1 2 2 1
 1 2 0 1 2 2 1 1 2 1 1 1 2 1 2]
debug gama:
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]] [0.5 0.5]
debug nan  [[0.5 0.5]
 [0.5 0.5]] [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]] [0.5 0.5]
 (A[0][0]*B[0][k]) / prob_sum 0.16666666666666666 0.3333333333333333
K:  1 Gama:  [[[0.  0.5 0. ]
  [0.  0.5 0. ]]

 [[0.  0.5 0. ]
  [0.  0.5 0. ]]] Q0:  [0.5 0.5]
debug:  0.5 ,  0.5 ,  0.5 , 0.5
updated Q = 
 [0.5 0.5]
debug gama:
 [[[0.  0.5 0. ]
  [0.  0.5 0. ]]

 [[0.  0.5 0. ]
  [0.  0.5 0. ]]] [0.5 0.5]
debug nan  [[0.5 0.5]
 [0.5 0.5]] [[0.33333333 0.33333333 0.33333333]
 [0.

  [0.5 0.5 0.5]]] Q0:  [0.5 0.5]
debug:  0.5 ,  0.5 ,  0.5 , 0.5
updated Q = 
 [0.5 0.5]
debug gama:
 [[[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]] [0.5 0.5]
debug nan  [[0.5 0.5]
 [0.5 0.5]] [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]] [0.5 0.5]
 (A[0][0]*B[0][k]) / prob_sum 0.16666666666666666 0.3333333333333333
K:  0 Gama:  [[[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]] Q0:  [0.5 0.5]
debug:  0.5 ,  0.5 ,  0.5 , 0.5
updated Q = 
 [0.5 0.5]
debug gama:
 [[[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]] [0.5 0.5]
debug nan  [[0.5 0.5]
 [0.5 0.5]] [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]] [0.5 0.5]
 (A[0][0]*B[0][k]) / prob_sum 0.16666666666666666 0.3333333333333333
K:  1 Gama:  [[[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]] Q0:  [0.5 0.5]
debug:  0.5 ,  0.5 ,  0.5 , 0.5
updated Q = 
 [0.5 0.5]
debug gama:
 [[[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5

K:  1 Gama:  [[[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]] Q0:  [0.5 0.5]
debug:  0.5 ,  0.5 ,  0.5 , 0.5
updated Q = 
 [0.5 0.5]
debug gama:
 [[[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]] [0.5 0.5]
debug nan  [[0.5 0.5]
 [0.5 0.5]] [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]] [0.5 0.5]
 (A[0][0]*B[0][k]) / prob_sum 0.16666666666666666 0.3333333333333333
K:  2 Gama:  [[[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]] Q0:  [0.5 0.5]
debug:  0.5 ,  0.5 ,  0.5 , 0.5
updated Q = 
 [0.5 0.5]
debug gama:
 [[[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]] [0.5 0.5]
debug nan  [[0.5 0.5]
 [0.5 0.5]] [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]] [0.5 0.5]
 (A[0][0]*B[0][k]) / prob_sum 0.16666666666666666 0.3333333333333333
K:  0 Gama:  [[[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]] Q0:  [0.5 0.5]
debug:  0.5 ,  0.5 ,  0.5 , 0.5
updated Q = 
 

debug nan  [[0.5 0.5]
 [0.5 0.5]] [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]] [0.5 0.5]
 (A[0][0]*B[0][k]) / prob_sum 0.16666666666666666 0.3333333333333333
K:  1 Gama:  [[[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]] Q0:  [0.5 0.5]
debug:  0.5 ,  0.5 ,  0.5 , 0.5
updated Q = 
 [0.5 0.5]
debug gama:
 [[[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]] [0.5 0.5]
debug nan  [[0.5 0.5]
 [0.5 0.5]] [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]] [0.5 0.5]
 (A[0][0]*B[0][k]) / prob_sum 0.16666666666666666 0.3333333333333333
K:  2 Gama:  [[[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]] Q0:  [0.5 0.5]
debug:  0.5 ,  0.5 ,  0.5 , 0.5
updated Q = 
 [0.5 0.5]
debug gama:
 [[[0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]]] [0.5 0.5]
debug nan  [[0.5 0.5]
 [0.5 0.5]] [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]] [0.5 0.5]
 (A[0][0]*B[0][k]) / prob

NameError: name 'Gama' is not defined

In [25]:
hmm.q.getQ()

array([0.5, 0.5])

In [26]:
hmm.fi.getFi()

array([[[[0.00835197, 0.26601028, 0.01041513],
         [0.0083464 , 0.26579913, 0.01027539]],

        [[0.00835755, 0.26594972, 0.01015623],
         [0.00835197, 0.26584   , 0.01041513]]],


       [[[0.00835197, 0.26601028, 0.01041513],
         [0.0083464 , 0.26579913, 0.01027539]],

        [[0.00835755, 0.26594972, 0.01015623],
         [0.00835197, 0.26584   , 0.01041513]]]])

In [ ]:
Gama > 0.0

In [ ]:
np.any(Gama == 0.0)

In [27]:
hmm.B

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [28]:
hmm.A

array([[0.5, 0.5],
       [0.5, 0.5]])